### ISSUE TITLE
Small Details

### ISSUE THREAD

**Issue by spfellers** [ghackett21/gig.io#42]
Accurate titles on all pages, or 1 gig.io title for all pages

404 page should be displayed if requesting a page that doesnt exist.

**Comment by ghackett21** [comment]
Which pages don't have accurate titles?

**Comment by ghackett21** [comment]
Ill look into the 404 issue

**Comment by ghackett21** [comment]
404 issue potential fix: move app.get('*'... to below the login get/post functions
look at admin page for how to set tab title: make all pages just gig.io

**Comment by ghackett21** [comment]
I fixed the 404 issue

**Comment by ghackett21** [comment]
Titles fixed by Sam
