### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by spfellers** [ghackett21/gig.io#43]
Only admins should be able to access admincp.

**Comment by ghackett21** [comment]
Is there any specific page where this is a problem? After testing it looks like it is already working properly

**Comment by ghackett21** [comment]
Looks like non-admin users can get to the admin page by typing in the address manually. I'll add a check in the onload function to check the admin status of the user. If they aren't an admin it will redirect to the main page

**Comment by ghackett21** [comment]
I ended up editing server.js so that it checks the user's admin status before sending the admin.html file and if the user is not an admin it sends index.html instead
